version: '3.4'

services:
   postgres: 
    container_name: threads-db
    image: postgres
    ports:
      - 5433:5432
    volumes:
       - postgres-data:/var/lib/postgresql/17/docker
    environment:
     POSTGRES_USER: postgres
     POSTGRES_DB: threads
     POSTGRES_PASSWORD: threads

volumes:
    postgres-data: